FROM python:3.10-slim
WORKDIR /app
COPY ../app .
CMD ["python", "main.py"]

#docker build -t python3.10 .
#docker run --name python python3.10
#mostrar todas las imagenes docker images
#mostrar todos los conteneodres docker ps -a
#eliminar un contenedor docker rm nombre_contenedor
#eliminar una imagen docker rmi nombre_imgen